const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='margin-state-v1';
const demoWeek=[
 {day:'Mon',date:'10',sleep:7,fixed:7,flex:3,care:1,commute:1,energy:4,stress:2},
 {day:'Tue',date:'11',sleep:6.5,fixed:8,flex:4,care:0,commute:1.5,energy:3,stress:3},
 {day:'Wed',date:'12',sleep:5.5,fixed:9,flex:6,care:2,commute:1.5,energy:2,stress:5},
 {day:'Thu',date:'13',sleep:6,fixed:8,flex:5,care:1,commute:2,energy:2,stress:4},
 {day:'Fri',date:'14',sleep:7,fixed:6,flex:3,care:1,commute:1,energy:3,stress:3},
 {day:'Sat',date:'15',sleep:8,fixed:2,flex:4,care:2,commute:.5,energy:3,stress:2},
 {day:'Sun',date:'16',sleep:8,fixed:1,flex:2,care:2,commute:0,energy:4,stress:2}
];
const actions=[
 {id:'orient',title:'Name five steady things',minutes:2,energy:['low','medium','high'],places:['public','private','outside'],silent:true,steps:'Look around slowly. Name five neutral things you can see, four sensations you can feel, and one sound you can hear.',reason:'It needs no privacy, movement, app or special equipment.'},
 {id:'exhale',title:'Longer-exhale reset',minutes:2,energy:['low','medium','high'],places:['public','private','outside'],silent:true,steps:'Breathe normally. For five rounds, let your exhale last a little longer than your inhale. Stop if you feel uncomfortable.',reason:'It is discreet and fits a very short, low-energy moment.'},
 {id:'water',title:'Water + one next step',minutes:5,energy:['low','medium'],places:['public','private'],silent:true,steps:'Drink some water if available. Write only the next physical action—not the whole project. Make it small enough to begin in two minutes.',reason:'It combines a physical pause with reduced decision load.'},
 {id:'walk',title:'Unhurried reset walk',minutes:10,energy:['medium','high'],places:['outside','public'],silent:true,steps:'Walk without trying to exercise. Let your eyes look farther away than a screen. Return when the timer ends.',reason:'Your context allows movement and a wider visual field.'},
 {id:'brain-dump',title:'Three-column brain dump',minutes:10,energy:['medium','high'],places:['private','public'],silent:true,steps:'Write three headings: must happen, can move, not mine. Put every open loop into one column. Choose one “must happen” item.',reason:'It reduces cognitive load without asking you to solve everything.'},
 {id:'sensory',title:'Lower the sensory volume',minutes:5,energy:['low','medium'],places:['private'],silent:true,steps:'Dim one light, silence one notification source, and reduce one uncomfortable sound or texture. Sit without adding another task.',reason:'You have some privacy and limited energy.'},
 {id:'stretch',title:'Desk release sequence',minutes:5,energy:['medium','high'],places:['private','outside'],silent:false,steps:'Unclench your jaw, lower your shoulders, open and close your hands, then stand or stretch gently within comfort.',reason:'It uses a little movement without becoming a workout.'},
 {id:'connection',title:'Send one low-pressure message',minutes:5,energy:['medium','high'],places:['private','public'],silent:true,steps:'Message one trusted person: “I am overloaded. I do not need solutions, but could you check in later?”',reason:'It asks for a specific kind of support without a long explanation.'},
 {id:'rest',title:'Protected nothing block',minutes:20,energy:['low','medium'],places:['private'],silent:true,steps:'Set the timer. Lie down or sit comfortably. No catching up, scrolling or planning. Let this block have no productivity target.',reason:'You have privacy and enough time for actual recovery.'}
];
function fresh(){return{week:structuredClone(demoWeek),checkin:{energy:3,stress:3,at:null},history:demoWeek.map((d,i)=>({day:d.day,energy:d.energy,stress:d.stress,sleep:d.sleep,at:`2026-08-${10+i}T12:00:00Z`})),learning:{},recent:[],helpfulWins:0,support:{name:'',signs:'',help:'',avoid:''},resource:{name:'',contact:''},settings:{contrast:false,calm:false,size:'normal'}}}
let state;try{state=JSON.parse(localStorage.getItem(STORE))||fresh()}catch{state=fresh()}if(!state.week?.length)state=fresh();state.history??=[];state.helpfulWins??=0;state.resource??={name:'',contact:''};state.learning??={};state.recent??=[];
let selectedDay=5,scenario={...state.week[selectedDay]},rescuedWeek=null,resetContext={minutes:5,energy:'medium',place:'public',quiet:false},currentAction=null,timer=null,timeLeft=0;
const save=()=>localStorage.setItem(STORE,JSON.stringify(state));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.id);toast.id=setTimeout(()=>t.classList.remove('show'),2300)}
function calc(d){const reserve=2,waking=24-d.sleep,available=waking-d.fixed-d.care-d.commute-reserve,friction=1+(5-d.energy)*.11+d.stress*.035,demand=d.flex*friction,margin=available-demand,debt=Math.max(0,-margin);let level='green';if(debt>1||d.sleep<5.75)level='red';else if(margin<2||d.sleep<7)level='amber';return{reserve,waking,available,demand,margin,debt,level,friction}}
const fmt=n=>`${n>=0?'+':''}${n.toFixed(1)}h`;
function showView(name){$$('.view').forEach(v=>{v.hidden=true;v.classList.remove('active')});$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const v=$(`#${name}View`);v.hidden=false;v.classList.add('active');if(name==='week')renderWeekLab();if(name==='reset')renderRecommendation(false);if(name==='support')renderSupport();scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));
function renderDashboard(){const results=state.week.map(calc),total=results.reduce((s,r)=>s+r.margin,0),red=results.filter(r=>r.level==='red').length,amber=results.filter(r=>r.level==='amber').length;$('#heroMargin').textContent=total.toFixed(1);$('#weekRibbon').innerHTML=state.week.map((d,i)=>{const r=results[i],height=Math.max(10,Math.min(100,50+r.margin*7));return`<article class="day-column ${r.level} ${i===5?'today':''}"><span class="day-state"></span><span class="day-name">${d.day}</span><span class="day-date">Aug ${d.date}</span><div class="capacity-bar"><i style="height:${height}%;--capacity:${height}%"></i></div><strong class="day-margin">${fmt(r.margin)}</strong><small>${r.level==='red'?'capacity debt':r.level==='amber'?'thin margin':'usable margin'}</small></article>`}).join('');$('#weekSummary').innerHTML=`<span class="summary-chip"><strong>${red}</strong> redline days</span><span class="summary-chip"><strong>${amber}</strong> thin-margin days</span><span class="summary-chip"><strong>${state.week.reduce((s,d)=>s+d.care,0).toFixed(1)}h</strong> care work counted</span><span class="summary-chip"><strong>${state.week.reduce((s,d)=>s+d.commute,0).toFixed(1)}h</strong> commuting counted</span>`;
 const worst=results.map((r,i)=>({...r,i})).sort((a,b)=>a.margin-b.margin)[0],wd=state.week[worst.i];$('#mainInsight').innerHTML=`<strong>${wd.day} is carrying more than it can hold.</strong><p>After sleep, fixed commitments, care work, commuting and a minimum recovery reserve, ${wd.day} has ${worst.debt.toFixed(1)} hours of capacity debt. Moving even one flexible block could protect the rest of the week.</p>`;
 const td=state.week[5],tr=results[5];$('#todayState').textContent=tr.level==='green'?'Room available':tr.level==='amber'?'Thin margin':'Redline';$('#todayState').className=`state-pill ${tr.level}`;$('#todayPlan').innerHTML=[['08:00','Care duties','Counted, not invisible'],['10:30','Assignment block',`${td.flex.toFixed(1)}h flexible demand`],['15:00','Unclaimed margin',tr.margin>0?`${tr.margin.toFixed(1)}h protected`:'No protected margin'],['19:30','Recovery reserve','2.0h minimum']].map(x=>`<div class="plan-row"><time>${x[0]}</time><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('');
 $('#energyRange').value=state.checkin.energy;$('#stressRange').value=state.checkin.stress;$('#energyValue').textContent=`${state.checkin.energy} / 5`;$('#stressValue').textContent=`${state.checkin.stress} / 5`;$('#checkinSaved').textContent=state.checkin.at?'Saved locally':'';
 renderTrends();renderFootprints();
}
function renderTrends(){const data=state.history.length?state.history.slice(-7):state.week.map(d=>({day:d.day,energy:d.energy,stress:d.stress,sleep:d.sleep}));$('#trendChart').innerHTML=data.map(d=>`<div class="trend-day" title="${d.day}: energy ${d.energy}, stress ${d.stress}, sleep ${d.sleep} hours"><i style="height:${d.energy*18}%"></i><i style="height:${d.stress*18}%"></i><i style="height:${Math.min(100,d.sleep*10)}%"></i><span>${d.day}</span></div>`).join('');const low=[...data].sort((a,b)=>(a.energy-a.stress)-(b.energy-b.stress))[0],avgSleep=data.reduce((s,d)=>s+d.sleep,0)/data.length;$('#trendInsight').textContent=`Energy was most stretched on ${low.day}. Average recorded sleep is ${avgSleep.toFixed(1)} hours. MARGIN shows association, not medical causation.`}
function renderFootprints(){const wins=state.helpfulWins||0,shown=Math.min(10,Math.max(5,wins));$('#footprints').innerHTML=Array.from({length:shown},(_,i)=>`<span class="footprint ${i<wins?'':'empty'}">${i<wins?'✓':'·'}</span>`).join('');$('#winsCount').textContent=`${wins} helpful moment${wins===1?'':'s'}`}
$('#demoBtn').addEventListener('click',()=>{state.week=structuredClone(demoWeek);state.history=demoWeek.map((d,i)=>({day:d.day,energy:d.energy,stress:d.stress,sleep:d.sleep,at:`2026-08-${10+i}T12:00:00Z`}));selectedDay=5;scenario={...state.week[5]};save();renderDashboard();toast('Demo week restored')});
['energy','stress'].forEach(k=>{$(`#${k}Range`).addEventListener('input',e=>{$(`#${k}Value`).textContent=`${e.target.value} / 5`})});
function commitCheckin(energy,stress,sleep=state.week[5].sleep){state.checkin={energy,stress,at:new Date().toISOString()};state.week[5].energy=energy;state.week[5].stress=stress;state.week[5].sleep=sleep;state.history.push({day:state.week[5].day,energy,stress,sleep,at:state.checkin.at});state.history=state.history.slice(-21);save();renderDashboard()}
$('#saveCheckin').addEventListener('click',()=>{commitCheckin(+$('#energyRange').value,+$('#stressRange').value);toast('Check-in saved on this device')});
$('#voiceCheckin').addEventListener('click',()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#voiceStatus').textContent='Voice check-in is unavailable in this browser. The sliders still work offline.';return}const rec=new SR();rec.lang='en-US';rec.interimResults=false;$('#voiceCheckin').classList.add('listening');$('#voiceStatus').textContent='Listening… speak naturally.';rec.onresult=e=>{const t=e.results[0][0].transcript.toLowerCase();let energy=3,stress=3,sleep=state.week[5].sleep;const sm=t.match(/(?:slept|sleep|got)\s+(\d+(?:\.\d+)?)\s*(?:hours?|hrs?)?/);if(sm)sleep=Math.max(3,Math.min(10,+sm[1]));if(/energy\s+(?:is\s+)?(?:very\s+)?low|exhausted|drained|no energy/.test(t))energy=1;else if(/energy\s+(?:is\s+)?high|energized|full of energy/.test(t))energy=5;else if(/energy\s+(?:is\s+)?medium|okay energy|steady/.test(t))energy=3;if(/stress\s+(?:is\s+)?(?:very\s+)?high|overwhelmed|flooded/.test(t))stress=5;else if(/stress\s+(?:is\s+)?low|calm|relaxed/.test(t))stress=1;else if(/stress\s+(?:is\s+)?medium|a bit stressed/.test(t))stress=3;commitCheckin(energy,stress,sleep);$('#voiceStatus').textContent=`Heard: “${t}” — sleep ${sleep}h, energy ${energy}/5, stress ${stress}/5.`;$('#voiceCheckin').classList.remove('listening')};rec.onerror=()=>{$('#voiceStatus').textContent='I could not hear that. Try again or use the sliders.';$('#voiceCheckin').classList.remove('listening')};rec.onend=()=>$('#voiceCheckin').classList.remove('listening');rec.start()});
$('#readInsight').addEventListener('click',()=>{if(!('speechSynthesis'in window)){toast('Read aloud is unavailable');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('#mainInsight').innerText);u.rate=.92;speechSynthesis.speak(u);toast('Reading insight aloud')});
function renderWeekLab(){const days=state.week;$('#dayPicker').innerHTML=days.map((d,i)=>`<button class="${i===selectedDay?'active':''}" data-day="${i}">${d.day}<br>${d.date}</button>`).join('');$$('#dayPicker button').forEach(b=>b.addEventListener('click',()=>{selectedDay=+b.dataset.day;scenario={...state.week[selectedDay]};renderWeekLab()}));['sleep','fixed','flex','care','commute'].forEach(k=>{$(`#${k}Input`).value=scenario[k];$(`#${k}Out`).textContent=`${scenario[k]}h`});renderScenario()}
['sleep','fixed','flex','care','commute'].forEach(k=>$(`#${k}Input`).addEventListener('input',e=>{scenario[k]=+e.target.value;$(`#${k}Out`).textContent=`${scenario[k]}h`;renderScenario()}));
function renderScenario(){const before=calc(state.week[selectedDay]),after=calc(scenario),delta=after.margin-before.margin;$('#scenarioTitle').textContent=`${state.week[selectedDay].day}: test a safer shape.`;const width=v=>`${Math.max(4,Math.min(100,50+v*7))}%`;$('#beforeBar').style.width=width(before.margin);$('#afterBar').style.width=width(after.margin);$('#beforeValue').textContent=fmt(before.margin);$('#afterValue').textContent=fmt(after.margin);$('#scenarioVerdict').innerHTML=`<strong>${delta>=0?'+':''}${delta.toFixed(1)} hours of breathing room</strong><p>${after.level==='red'?'This scenario still creates capacity debt. Keep reducing flexible demand or protect more sleep.':after.level==='amber'?'This is safer, but the margin remains thin.':'This plan keeps a usable recovery margin without pretending every hour is productive.'}</p>`;$('#scenarioWhy').innerHTML=[['Waking time',`${after.waking.toFixed(1)}h`],['Capacity after fixed life',`${after.available.toFixed(1)}h`],['Friction-adjusted demand',`${after.demand.toFixed(1)}h`],['Recovery reserve','2.0h protected']].map(x=>`<div class="why-row"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const moves=[];if(scenario.sleep<7)moves.push(['Protect 30 more minutes of sleep','+0.5h']);if(scenario.flex>2)moves.push(['Move 60 minutes of flexible work','+1.0h']);if(scenario.commute>1)moves.push(['Combine or remote one trip','up to +0.5h']);if(scenario.fixed>8)moves.push(['Ask which fixed block can flex','conversation']);moves.push(['Keep the recovery reserve untouched','protect 2.0h']);$('#moveSuggestions').innerHTML=moves.slice(0,4).map(x=>`<div class="suggestion-row"><p>${x[0]}</p><strong>${x[1]}</strong></div>`).join('')}
$('#resetScenario').addEventListener('click',()=>{scenario={...state.week[selectedDay]};renderWeekLab()});$('#saveScenario').addEventListener('click',()=>{state.week[selectedDay]={...scenario};save();renderDashboard();renderWeekLab();toast(`${state.week[selectedDay].day} updated safely`)});
function optimizeWeek(source){const w=structuredClone(source),moves=[];for(let n=0;n<40;n++){const rs=w.map(calc),from=rs.map((r,i)=>({...r,i})).filter(x=>w[x.i].flex>=.5&&x.margin<2).sort((a,b)=>a.margin-b.margin)[0],to=rs.map((r,i)=>({...r,i})).filter(x=>!from||x.i!==from.i).sort((a,b)=>b.margin-a.margin)[0];if(!from||!to||to.margin<2.2)break;w[from.i].flex-=.5;w[to.i].flex+=.5;moves.push({from:w[from.i].day,to:w[to.i].day,hours:.5})}const before=source.map(calc),after=w.map(calc);return{week:w,moves,beforeDebt:before.reduce((s,r)=>s+r.debt,0),afterDebt:after.reduce((s,r)=>s+r.debt,0),beforeRed:before.filter(r=>r.level==='red').length,afterRed:after.filter(r=>r.level==='red').length}}
$('#rescueWeek').addEventListener('click',()=>{const o=optimizeWeek(state.week);rescuedWeek=o.week;const grouped=[];o.moves.forEach(m=>{const k=`${m.from} → ${m.to}`,g=grouped.find(x=>x.k===k);if(g)g.h+=m.hours;else grouped.push({k,h:m.hours})});$('#rescueReport').hidden=false;$('#rescueReport').innerHTML=`<strong>${(o.beforeDebt-o.afterDebt).toFixed(1)}h less capacity debt</strong><p>Redline days: ${o.beforeRed} before, ${o.afterRed} after. Flexible work only was moved; sleep, fixed commitments, care and commuting were untouched.</p>${grouped.slice(0,6).map(g=>`<div class="rescue-move"><span>${g.k}</span><b>${g.h.toFixed(1)}h moved</b></div>`).join('')}<p>Check every suggested move against real deadlines before applying it.</p>`;$('#applyRescue').hidden=!o.moves.length;if(!o.moves.length)toast('No safe redistribution found without changing fixed life')});$('#applyRescue').addEventListener('click',()=>{if(!rescuedWeek)return;state.week=structuredClone(rescuedWeek);scenario={...state.week[selectedDay]};save();renderDashboard();renderWeekLab();$('#rescueReport').hidden=false;toast('Rescued week applied locally')});
function parseICSDate(raw){const m=raw?.match(/(\d{4})(\d{2})(\d{2})(?:T(\d{2})(\d{2})(\d{2})?)?/);if(!m)return null;return new Date(+m[1],+m[2]-1,+m[3],+(m[4]||0),+(m[5]||0),+(m[6]||0))}$('#calendarImport').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const text=(await file.text()).replace(/\r?\n[ \t]/g,''),events=[...text.matchAll(/BEGIN:VEVENT([\s\S]*?)END:VEVENT/g)].map(x=>x[1]);let added=0,count=0;for(const block of events){const start=parseICSDate(block.match(/DTSTART[^:]*:([^\r\n]+)/)?.[1]),end=parseICSDate(block.match(/DTEND[^:]*:([^\r\n]+)/)?.[1]);if(!start||!end||end<=start)continue;const idx=(start.getDay()+6)%7,h=Math.min(12,(end-start)/36e5);state.week[idx].fixed=Math.min(14,state.week[idx].fixed+h);added+=h;count++}save();scenario={...state.week[selectedDay]};renderDashboard();renderWeekLab();$('#calendarStatus').textContent=`Imported ${count} events and counted ${added.toFixed(1)} fixed hours locally.`}catch{$('#calendarStatus').textContent='That calendar could not be read. Export it as a standard .ics file and try again.'}});$('#exportCalendar').addEventListener('click',()=>{const pad=n=>String(n).padStart(2,'0'),base=new Date(2026,7,10),lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//MARGIN//Safer Week//EN'];state.week.forEach((d,i)=>{const date=new Date(base);date.setDate(base.getDate()+i);const ds=`${date.getFullYear()}${pad(date.getMonth()+1)}${pad(date.getDate())}`,flexMinutes=Math.round(d.flex*60),endH=14+Math.floor(flexMinutes/60),endM=flexMinutes%60;lines.push('BEGIN:VEVENT',`UID:margin-flex-${i}@local`,`DTSTART:${ds}T140000`,`DTEND:${ds}T${pad(Math.min(23,endH))}${pad(endM)}00`,`SUMMARY:MARGIN flexible work block (${d.flex.toFixed(1)}h)`,'DESCRIPTION:Review this suggested block against real deadlines.','END:VEVENT','BEGIN:VEVENT',`UID:margin-recovery-${i}@local`,`DTSTART:${ds}T200000`,`DTEND:${ds}T220000`,'SUMMARY:Protected recovery margin','END:VEVENT')});lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')],{type:'text/calendar'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='margin-safer-week.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('#calendarStatus').textContent='Safer week exported. Review times before adding it to your calendar.'});
function bindChoice(group,key,attr){$$(`${group} button`).forEach(b=>b.addEventListener('click',()=>{$$(`${group} button`).forEach(x=>x.classList.remove('active'));b.classList.add('active');resetContext[key]=attr==='minutes'?+b.dataset[attr]:b.dataset[attr]}))}bindChoice('#timeChoices','minutes','minutes');bindChoice('#resetEnergy','energy','energy');bindChoice('#placeChoices','place','place');$('#quietOnly').addEventListener('change',e=>resetContext.quiet=e.target.checked);
function contextKey(){return`${resetContext.energy}:${resetContext.place}:${resetContext.quiet?'quiet':'any'}`}
function actionScore(a){if(a.minutes>resetContext.minutes)return-999;let s=45+(resetContext.minutes-a.minutes)*1.2;if(a.energy.includes(resetContext.energy))s+=16;else s-=8;if(a.places.includes(resetContext.place))s+=15;else s-=12;if(resetContext.quiet&&a.silent)s+=10;if(resetContext.quiet&&!a.silent)s-=25;const learned=state.learning?.[a.id]?.[contextKey()];if(learned)s+=(learned.mean-.5)*36;if(state.recent.includes(a.id))s-=14;return s}
function renderRecommendation(find=true){if(!find&&!currentAction)return;const ranked=actions.map(a=>({...a,score:actionScore(a)})).filter(a=>a.score>-100).sort((a,b)=>b.score-a.score);if(!ranked.length){$('#recommendation').innerHTML='<span class="rec-icon">↺</span><h2>Try a little more time or fewer constraints.</h2><p>No action in the local library fits all selected limits safely.</p>';return}currentAction=ranked[0];const r=currentAction;$('#recommendation').classList.remove('empty-rec');$('#recommendation').innerHTML=`<span class="rec-icon">${r.silent?'◌':'↗'}</span><h2>${r.title}</h2><p>${r.steps}</p><p class="rec-why">Why this: ${r.reason}</p>`;$('#timerBox').hidden=false;$('#feedbackBox').hidden=false;timeLeft=r.minutes*60;updateTimer();$('#learningBadge').textContent=state.learning?.[r.id]?.[contextKey()]?'Adapted to feedback':'First local estimate'}
$('#findReset').addEventListener('click',()=>{resetContext.quiet=$('#quietOnly').checked;renderRecommendation(true)});function updateTimer(){const m=Math.floor(timeLeft/60),s=timeLeft%60;$('#timerDisplay').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}$('#timerBtn').addEventListener('click',()=>{if(timer){clearInterval(timer);timer=null;$('#timerBtn').textContent='Resume';return}$('#timerBtn').textContent='Pause';timer=setInterval(()=>{timeLeft--;updateTimer();if(timeLeft<=0){clearInterval(timer);timer=null;$('#timerBtn').textContent='Done';toast('Reset complete — notice, do not grade yourself')}},1000)});
$$('[data-feedback]').forEach(b=>b.addEventListener('click',()=>{if(!currentAction)return;state.learning[currentAction.id]??={};const k=contextKey(),old=state.learning[currentAction.id][k]||{n:0,mean:.5},reward=b.dataset.feedback==='yes'?1:0;old.mean=(old.mean*old.n+reward)/(old.n+1);old.n++;state.learning[currentAction.id][k]=old;state.recent=[currentAction.id,...state.recent.filter(x=>x!==currentAction.id)].slice(0,2);if(reward)state.helpfulWins=(state.helpfulWins||0)+1;save();renderFootprints();toast(reward?'Helpful moment saved — no streak required':'Feedback learned without judgment');renderRecommendation(true)}));
function renderSupport(){const s=state.support;$('#supportName').value=s.name;$('#overloadSigns').value=s.signs;$('#helpfulActions').value=s.help;$('#avoidActions').value=s.avoid;$('#resourceName').value=state.resource?.name||'';$('#resourceContact').value=state.resource?.contact||'';updateSupportPreview();renderResource()}function renderResource(){const r=state.resource||{};$('#savedResource').innerHTML=r.name||r.contact?`<div class="resource-pill"><strong>${r.name||'Trusted support'}</strong><span>${r.contact||'Contact details not added'}</span></div>`:''}function updateSupportPreview(){const s={name:$('#supportName').value.trim(),signs:$('#overloadSigns').value.trim(),help:$('#helpfulActions').value.trim(),avoid:$('#avoidActions').value.trim()};$('#previewName').textContent=s.name?`How to support ${s.name}`:'A small guide for a hard moment';$('#previewSigns').textContent=s.signs||'I may have less capacity than usual.';$('#previewHelp').textContent=s.help||'Ask what kind of support I want.';$('#previewAvoid').textContent=s.avoid||'Assuming silence means I do not care.';return s}['supportName','overloadSigns','helpfulActions','avoidActions'].forEach(id=>$(`#${id}`).addEventListener('input',updateSupportPreview));$('#updateCard').addEventListener('click',()=>{state.support=updateSupportPreview();save();toast('Support Card saved locally')});$('#clearSupport').addEventListener('click',()=>{state.support={name:'',signs:'',help:'',avoid:''};renderSupport();save();toast('Support Card cleared')});$('#copyCard').addEventListener('click',async()=>{const s=updateSupportPreview(),txt=`How to support ${s.name||'me'}\n\nYou may notice: ${s.signs||'I may have less capacity than usual.'}\n\nWhat helps: ${s.help||'Ask what kind of support I want.'}\n\nPlease avoid: ${s.avoid||'Assuming silence means I do not care.'}`;try{await navigator.clipboard.writeText(txt);toast('Support Card copied')}catch{toast('Clipboard unavailable')}});$('#printCard').addEventListener('click',()=>print());
function canvasWrap(ctx,text,x,y,maxWidth,lineHeight,maxLines=4){const words=String(text).split(/\s+/);let line='',lines=[];for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));return y+Math.min(lines.length,maxLines)*lineHeight}
$('#downloadCard').addEventListener('click',()=>{const s=updateSupportPreview(),c=document.createElement('canvas');c.width=1200;c.height=675;const x=c.getContext('2d');x.fillStyle='#18201d';x.fillRect(0,0,c.width,c.height);x.fillStyle='#d8f36a';x.beginPath();x.arc(1080,90,42,0,Math.PI*2);x.fill();x.fillStyle='#18201d';x.font='900 36px system-ui';x.textAlign='center';x.fillText('M',1080,103);x.textAlign='left';x.fillStyle='#d8f36a';x.font='800 18px system-ui';x.fillText('HOW TO SUPPORT ME',70,75);x.fillStyle='#ffffff';x.font='700 48px system-ui';x.fillText(s.name?`How to support ${s.name}`:'A small guide for a hard moment',70,145);const blocks=[['YOU MAY NOTICE',s.signs||'I may have less capacity than usual.'],['WHAT HELPS',s.help||'Ask what kind of support I want.'],['PLEASE AVOID',s.avoid||'Assuming silence means I do not care.']];let y=225;blocks.forEach(([h,t])=>{x.fillStyle='#98aaa2';x.font='800 15px system-ui';x.fillText(h,70,y);x.fillStyle='#ffffff';x.font='24px system-ui';y=canvasWrap(x,t,70,y+38,1030,32,3)+35});x.fillStyle='#98aaa2';x.font='15px system-ui';x.fillText('This card shares preferences, not a diagnosis. Created privately with MARGIN.',70,630);const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='margin-support-card.png';a.click();toast('Support Card image downloaded')});
$('#generateBoundary').addEventListener('click',()=>{const audience=$('#boundaryAudience').value,request=$('#boundaryRequest').value,alt=$('#boundaryDate').value.trim()||'a short alternative we can agree on',hello=audience==='lecturer'?'Hello,':audience==='manager'?'Hello,':'Hi team,',context=audience==='team'?'I have reviewed our current workload and my available capacity.':'I am writing early because several fixed commitments have created a temporary capacity conflict.',ask=request==='extension'?`Could we agree on a short extension, ideally ${alt}?`:request==='scope'?`Could we reduce the immediate scope to ${alt}?`:request==='meeting'?`Could we have a brief meeting to reprioritize, ideally ${alt}?`:`Could we adjust the schedule or shift to ${alt}?`;$('#boundaryOutput').value=`${hello}\n\n${context} I want to communicate before this affects the quality or reliability of my work.\n\n${ask}\n\nI can still complete the highest-priority part and will confirm the revised plan clearly. I prefer to keep personal details private, but I am raising the conflict as early as possible.\n\nThank you for considering this request.`});$('#copyBoundary').addEventListener('click',async()=>{if(!$('#boundaryOutput').value){toast('Generate a draft first');return}try{await navigator.clipboard.writeText($('#boundaryOutput').value);toast('Boundary message copied')}catch{toast('Clipboard unavailable')}});
$('#saveResource').addEventListener('click',()=>{state.resource={name:$('#resourceName').value.trim(),contact:$('#resourceContact').value.trim()};save();renderResource();toast('Human support saved locally')});$('#exportData').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`margin-data-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});$('#deleteData').addEventListener('click',()=>{if(confirm('Delete this week, check-ins, Support Card and local learning?')){localStorage.removeItem(STORE);state=fresh();save();renderDashboard();renderSupport();toast('All local MARGIN data deleted')}});
const calmSteps=[
 {title:'Nothing else is required for this minute.',copy:'Put both feet somewhere supported. Let the screen wait.',breathe:false,next:'One next step'},
 {title:'Make the exhale a little longer.',copy:'Breathe normally. If it feels comfortable, let the next few exhales last slightly longer than the inhales. Stop if you feel dizzy.',breathe:true,next:'I am ready'},
 {title:'Choose only what comes next.',copy:'Not the whole day. Not the whole problem. Name one physical action small enough to begin in two minutes.',breathe:false,next:'One final step'},
 {title:'Continue, pause, or ask for a person.',copy:'All three are valid. The goal is not to feel perfect; it is to reduce the next moment’s load.',breathe:false,next:'Close Calm Now'}
];let calmIndex=0;function renderCalm(){const s=calmSteps[calmIndex];$('#calmNumber').textContent=`STEP ${calmIndex+1} OF ${calmSteps.length}`;$('#calmTitle').textContent=s.title;$('#calmCopy').textContent=s.copy;$('#calmProgress').style.width=`${(calmIndex+1)/calmSteps.length*100}%`;$('#breathingPacer').hidden=!s.breathe;$('#calmBack').disabled=calmIndex===0;$('#calmNext').innerHTML=`${s.next} <span>→</span>`}
$('#calmNowBtn').addEventListener('click',()=>{calmIndex=0;renderCalm();$('#calmOverlay').hidden=false;document.body.style.overflow='hidden'});$('#closeCalm').addEventListener('click',()=>{$('#calmOverlay').hidden=true;document.body.style.overflow=''});$('#calmNext').addEventListener('click',()=>{if(calmIndex===calmSteps.length-1){$('#calmOverlay').hidden=true;document.body.style.overflow='';return}calmIndex++;renderCalm()});$('#calmBack').addEventListener('click',()=>{if(calmIndex>0){calmIndex--;renderCalm()}});$('#calmRead').addEventListener('click',()=>{if(!('speechSynthesis'in window)){toast('Read aloud unavailable');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${calmSteps[calmIndex].title} ${calmSteps[calmIndex].copy}`);u.rate=.86;speechSynthesis.speak(u)});$('#humanHelp').addEventListener('click',()=>{$('#calmOverlay').hidden=true;document.body.style.overflow='';showView('support');setTimeout(()=>$('#resourceName').focus(),350)});
$('#accessBtn').addEventListener('click',()=>$('#accessPanel').hidden=!$('#accessPanel').hidden);$('#closeAccess').addEventListener('click',()=>$('#accessPanel').hidden=true);$('#contrastToggle').addEventListener('change',e=>{state.settings.contrast=e.target.checked;applySettings()});$('#calmToggle').addEventListener('change',e=>{state.settings.calm=e.target.checked;applySettings()});$$('[data-size]').forEach(b=>b.addEventListener('click',()=>{state.settings.size=b.dataset.size;$$('[data-size]').forEach(x=>x.classList.toggle('active',x===b));applySettings()}));function applySettings(){document.body.classList.toggle('high-contrast',state.settings.contrast);document.body.classList.toggle('calm',state.settings.calm);document.body.classList.toggle('large-text',state.settings.size==='large');$('#contrastToggle').checked=state.settings.contrast;$('#calmToggle').checked=state.settings.calm;$$('[data-size]').forEach(b=>b.classList.toggle('active',b.dataset.size===state.settings.size));save()}
renderDashboard();applySettings();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
